import {
  Brain,
  Database,
  Bot,
  Code2,
  Coffee,
  Target,
} from "lucide-react";

export const categories = [
  {
    title: "DSA Arena",
    description: "Master Data Structures & Algorithms.",
    players: "2.4K Online",
    difficulty: "Hard",
    xp: "+120 XP",
    icon: "Brain",
    color: "text-cyan-400",
  },
  {
    title: "Python Clash",
    description: "Battle with Python coding challenges.",
    players: "1.8K Online",
    difficulty: "Medium",
    xp: "+90 XP",
    icon: "Code2",
    color: "text-yellow-400",
  },
  {
    title: "SQL Duel",
    description: "Write optimized SQL queries.",
    players: "900 Online",
    difficulty: "Medium",
    xp: "+80 XP",
    icon: "Database",
    color: "text-green-400",
  },
  {
    title: "Java Championship",
    description: "Object-Oriented Programming battles.",
    players: "1.1K Online",
    difficulty: "Hard",
    xp: "+100 XP",
    icon: "Coffee",
    color: "text-orange-400",
  },
  {
    title: "AI Challenge",
    description: "Machine Learning & Prompt Engineering.",
    players: "750 Online",
    difficulty: "Expert",
    xp: "+150 XP",
    icon: "Bot",
    color: "text-pink-400",
  },
  {
    title: "Aptitude Rush",
    description: "Logical reasoning & quantitative aptitude.",
    players: "3.1K Online",
    difficulty: "Easy",
    xp: "+60 XP",
    icon: "Target",
    color: "text-violet-400",
  },
];