FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD [
"gunicorn",
"-k",
"uvicorn.workers.UvicornWorker",
"-w",
"4",
"-b",
"0.0.0.0:8000",
"app.main:app"
]