"""Initial database schema

Revision ID: dd495117949b
Revises: 
Create Date: 2026-07-05 11:02:25.721683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd495117949b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_os', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_refresh_tokens_token'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('github', sa.String(length=500), nullable=True),
    sa.Column('portfolio', sa.String(length=500), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('experience', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=False),
    sa.Column('placement_score', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_strengths', sa.JSON(), nullable=False),
    sa.Column('ai_weaknesses', sa.JSON(), nullable=False),
    sa.Column('ai_recommendations', sa.JSON(), nullable=False),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_email'), 'resumes', ['email'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.drop_table('interview_questions')
    op.drop_table('battle_participants')
    op.drop_table('developer_api_usages')
    op.drop_index(op.f('ix_problems_slug'), table_name='problems')
    op.drop_table('problems')
    op.drop_table('battle_rooms')
    op.drop_table('interview_answers')
    op.drop_table('tournament_matches')
    op.drop_table('api_request_logs')
    op.drop_table('battle_submissions')
    op.drop_table('daily_challenges')
    op.drop_table('memory')
    op.drop_table('streak')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_table('roadmap_weeks')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_code_submissions_user_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    op.drop_table('test_cases')
    op.drop_table('roadmap_tasks')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_table('developer_api_keys')
    op.drop_table('xp')
    op.drop_table('achievements')
    op.drop_table('webhooks')
    op.drop_table('battle_results')
    op.drop_table('tournament_participants')
    op.drop_table('tournaments')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('coding_rating', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('placement_score', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('resume_score', sa.Integer(), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('users', 'resume_score')
    op.drop_column('users', 'placement_score')
    op.drop_column('users', 'coding_rating')
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'role')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'website')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'username')
    op.create_table('tournaments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=30), nullable=False),
    sa.Column('max_players', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_participants',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tournament_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_results',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('battle_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('winner_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('total_players', sa.INTEGER(), nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battle_rooms.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('secret', sa.VARCHAR(length=128), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=False),
    sa.Column('unlocked', sa.BOOLEAN(), nullable=False),
    sa.Column('earned_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('total_xp', sa.INTEGER(), nullable=False),
    sa.Column('weekly_xp', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('developer_api_keys',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('scope', sa.VARCHAR(length=30), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('roadmaps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('target_company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), nullable=False),
    sa.Column('estimated_hours', sa.INTEGER(), nullable=False),
    sa.Column('progress', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('week_id', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estimated_minutes', sa.INTEGER(), nullable=False),
    sa.Column('reward_xp', sa.INTEGER(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['roadmap_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('problem_id', sa.INTEGER(), nullable=False),
    sa.Column('input_data', sa.TEXT(), nullable=False),
    sa.Column('expected_output', sa.TEXT(), nullable=False),
    sa.Column('is_sample', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('problem_id', sa.INTEGER(), nullable=False),
    sa.Column('language', sa.VARCHAR(length=30), nullable=False),
    sa.Column('source_code', sa.TEXT(), nullable=False),
    sa.Column('verdict', sa.VARCHAR(length=50), nullable=False),
    sa.Column('execution_time', sa.INTEGER(), nullable=False),
    sa.Column('memory_used', sa.INTEGER(), nullable=False),
    sa.Column('passed_tests', sa.INTEGER(), nullable=False),
    sa.Column('total_tests', sa.INTEGER(), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submissions_user_id'), 'code_submissions', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=500), nullable=False),
    sa.Column('bio', sa.VARCHAR(length=500), nullable=False),
    sa.Column('college', sa.VARCHAR(length=200), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=100), nullable=False),
    sa.Column('graduation_year', sa.INTEGER(), nullable=False),
    sa.Column('target_company', sa.VARCHAR(length=120), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('roadmap_weeks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('roadmap_id', sa.INTEGER(), nullable=False),
    sa.Column('week_number', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('objective', sa.VARCHAR(length=500), nullable=False),
    sa.Column('completion', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=100), nullable=False),
    sa.Column('interview_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=30), nullable=False),
    sa.Column('total_questions', sa.INTEGER(), nullable=False),
    sa.Column('overall_score', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('streak',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('current_streak', sa.INTEGER(), nullable=False),
    sa.Column('best_streak', sa.INTEGER(), nullable=False),
    sa.Column('last_active', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_challenges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_submissions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('battle_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('language', sa.VARCHAR(length=30), nullable=False),
    sa.Column('verdict', sa.VARCHAR(length=50), nullable=False),
    sa.Column('passed_tests', sa.INTEGER(), nullable=False),
    sa.Column('total_tests', sa.INTEGER(), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battle_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_request_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=255), nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.Column('response_time', sa.FLOAT(), nullable=False),
    sa.Column('client_ip', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_matches',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tournament_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('round_number', sa.INTEGER(), nullable=False),
    sa.Column('battle_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('player_one_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('player_two_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('winner_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=False),
    sa.Column('feedback', sa.TEXT(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_rooms',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=30), nullable=False),
    sa.Column('problem_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('max_players', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('input_format', sa.TEXT(), nullable=False),
    sa.Column('output_format', sa.TEXT(), nullable=False),
    sa.Column('constraints', sa.TEXT(), nullable=False),
    sa.Column('sample_input', sa.TEXT(), nullable=False),
    sa.Column('sample_output', sa.TEXT(), nullable=False),
    sa.Column('explanation', sa.TEXT(), nullable=False),
    sa.Column('xp_reward', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_slug'), 'problems', ['slug'], unique=1)
    op.create_table('developer_api_usages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('developer_api_key_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=False),
    sa.Column('last_used', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['developer_api_key_id'], ['developer_api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_participants',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('battle_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battle_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('sequence', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('expected_topics', sa.TEXT(), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_email'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
